Update docker images to new versions of Ubuntu, oneDNN, CMake, CUDA; restructured Docerfiles
- Bump CMake to 3.18.2
- Bump oneDNN to 1.6.2
- Bump to Ubuntu 20.04
- Seperate images for clang-format, clang-tidy, coverage, Cuda build
  with clang, gcc and clang with python bindings
- Dockerfiles for clang and gcc rely on the package manager for the
  compilers
- Updated test scripts, they test more and should error our earlier
- Nightly docker job created
- Docker build script updated
- Include CI job, to build docker images on changes

diff --git a/tools/docker/DocFileCuda b/tools/docker/DocFileCuda
--- a/tools/docker/DocFileCuda
+++ b/tools/docker/DocFileCuda
@@ -1,81 +1,69 @@
 # Provide an argument to choose the compiler version from the command line
 ARG CUDA_VERSION=10.2
-
-FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu18.04 as base
+ARG UBUNTU_VERSION=18.04 
+ 
+# Start with our CMake image 
+FROM elsa/cmake:${UBUNTU_VERSION} AS copy-cmake
 MAINTAINER Tobias Lasser <lasser@in.tum.de>
+MAINTAINER David Frannk <frankd@in.tum.de>
 LABEL Description="Cuda develop with cmake/git and clang"
+ 
+ARG CUDA_VERSION
+ARG UBUNTU_VERSION
+  
+# Take the cuda ubuntu devel image from the cuda repo
+FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION} AS base
+ 
+# Copy the CMake install over to this image 
+COPY --from=copy-cmake /tmp/cmake-install /usr/local
 
-ADD scripts/ /tmp/scripts/
-RUN /tmp/scripts/install_base.sh
-RUN apt-get update -qq && apt-get --no-install-recommends install -qq swig libncurses5-dev libedit-dev libpthread-stubs0-dev lcov \
-  && rm -rf /var/lib/apt/lists/*
-
-FROM base as build-cmake
-
-# CMake version
-ARG CMAKE_VERSION=3.16
-ARG CMAKE_VERSION_PATCH=4
-ARG CMAKE_DIR=cmake-${CMAKE_VERSION}.${CMAKE_VERSION_PATCH}
-
-RUN bash /tmp/scripts/install_cmake.sh "${CMAKE_VERSION}" "${CMAKE_DIR}"
-
-FROM base as cmake
-COPY --from=build-cmake /tmp/cmake-install /usr/local
-
-FROM cmake as clone-clang
-
-ARG CLANG_VERSION=9.0.1
-ARG CLANG_TAG=llvmorg-${CLANG_VERSION}
-
-RUN git clone --depth 1 --branch ${CLANG_TAG} https://github.com/llvm/llvm-project.git /tmp/llvm_project/
-
-FROM cmake as configure-clang
-COPY --from=clone-clang /tmp/llvm_project/ /tmp/llvm_project/
-
-RUN mkdir -p /tmp/llvm_build/ && mkdir -p /tmp/llvm_install/ \
-  && cmake -S /tmp/llvm_project/llvm/ -B /tmp/llvm_build/ -GNinja -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi;openmp" \
-           -DCMAKE_INSTALL_PREFIX=/tmp/llvm_install/ -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="host;NVPTX" -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON
-
-### Build LLVM/clang
-FROM cmake as build-clang
-COPY --from=configure-clang /tmp/llvm_project/ /tmp/llvm_project/
-COPY --from=configure-clang /tmp/llvm_build/ /tmp/llvm_build/
-
-# install a reduced version of clang (due to LLVM_INSTALL_TOOLCHAIN_ONLY=ON)
-WORKDIR /tmp/llvm_build/
-RUN ninja install
-WORKDIR /
-
-### Set base for clang ###
-FROM cmake as clang
-COPY --from=build-clang /tmp/llvm_install/ /usr/local/
-
+# Add scripts so we can install using them
+ADD scripts/install_base.sh /tmp/scripts/install_base.sh
+ 
+# Install our base image here 
+RUN /tmp/scripts/install_base.sh 
+ 
+ARG UBUNTU_VERSION 
+ARG GCC_VERSION=8
+ 
+# This avoid trouble configuring tzdata, which requires user input but fails in docker build step
+ENV TZ=Europe/Berlin
+RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
+ 
+# For Ubuntu 18, we hadd the ubuntu-toolchain repo and then install GCC-9 for both Ubuntu 20 and 18 
+RUN set -ex; \
+    echo "Version: ${UBUNTU_VERSION}" && \
+    apt update && apt upgrade -qqy \
+    && apt --no-install-recommends install build-essential software-properties-common -qqy; \
+    if (test "${UBUNTU_VERSION}" = "18.04" ); then \
+        add-apt-repository ppa:ubuntu-toolchain-r/test -qqy && apt update; \
+    fi; \
+    apt --no-install-recommends install gcc-${GCC_VERSION} g++-${GCC_VERSION} -qqy \
+    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_VERSION} 100 \
+       --slave /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} \
+    && update-alternatives --config gcc && ldconfig \
+    && apt autoremove && apt autoclean \
+    && rm -rf /var/lib/apt/lists/*
+  
 # Set enviorment variables
-ENV CC="/usr/local/bin/clang"
-ENV CXX="/usr/local/bin/clang++"
-ENV PATH="$PATH:/usr/local/bin/"
-ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu/:/usr/local/lib/"
+ENV CC="gcc"
+ENV CXX="g++"
 
-FROM clang as build-dnnl
-ARG DNNL_VERSION=1.1.1
-RUN /tmp/scripts/install_inteldnnl.sh ${DNNL_VERSION}
+# Install oneDNN using the compiler we'll be using with elsa
+FROM base AS build-onednn
+ 
+# Add oneDNN install script 
+ADD scripts/install_intel-oneDNN.sh /tmp/scripts/install_intel-oneDNN.sh 
+ 
+ARG ONEDNN_VERSION=1.6.2
+RUN /tmp/scripts/install_intel-oneDNN.sh ${ONEDNN_VERSION}
 
-FROM clang as dnnl
-COPY --from=build-dnnl /tmp/dnnl_install/ /usr/local/
+# Copy it to our base image 
+FROM base as onednn
+COPY --from=build-onednn /tmp/onednn_install/ /usr/local/
 
-ADD tests/ /tmp/tests/
-
-# setup conan home directory, to be in the cache of our CI pipeline
-ENV CONAN_USER_HOME=/cache
-
-# setup conan for clang
-RUN conan profile new default --detect \
- && conan profile update settings.compiler.libcxx=libc++ default \
- && conan profile update settings.compiler.cppstd=17 default \
- && conan profile update env.CC=clang default \
- && conan profile update env.CXX=clang++ default \
- && conan profile update env.CONAN_CMAKE_GENERATOR=Ninja default \
- && conan profile show default
+# Add the test scripts 
+ADD tests/test_elsa.sh /tmp/tests/test_elsa.sh
 
 CMD bash
 
